name: gha-demo1

on:
  push:
    branches: [ main ]
    paths-ignore: [ .github/** ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:
    inputs:
      environment:
        description: 'Env to deploy to'
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The job was triggered by event: ${{ github.event_name }}"
          echo "The name of your branch is ${{ github.ref }} and your repo is ."
          echo "Display NEV_NAME from Environment: ${{ vars.ENV_NAME }} "
          echo "job name: ${{ vars.JOB_NAME }}"
          env
          
      
  ListFile:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source file
        uses: actions/checkout@v3.3.0

      - name: List files in the repo
        run: |
          echo "The repo ${{ github.repository }} contains the following files:"
          tree              
