name: CI Build for Docker Action
on:
  push:
    branches: [ demo1 ]
    paths: [ hello-world-docker-ci/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Run hello docker container action
        id: hello-action1
        uses: ./hello-world-docker-ci
        with:
          who-to-greet: '@DeepSeek'

      - name: Output time set in the container
        # run: echo "The time was ${{ steps.hello-action1.outputs.time }} by ${{ steps.hello-action1.outputs.who }} when the action said hello"
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
